name: CI

on: [push, pull_request]

jobs:
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npm run typecheck
  # test:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v3
  #     - name: Install Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.x
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: npm test
  package:
    name: Package
    needs: [
      types,
      # test
    ]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Write .env
        run: node create-env.js
        env:
          CG_PUBLIC_URL: ${{secrets.CG_PUBLIC_URL}}
          CG_API_URL: ${{secrets.CG_API_URL}}
          SOCKET_SERVER_URL: ${{secrets.SOCKET_SERVER_URL}}
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
      - name: Package
        run: npm run package
      - uses: actions/upload-artifact@v3
        with:
          name: Chatguessr-${{runner.os}}
          path: out/*/
