name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    name: Publish release
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Write .env
        run: node create-env.js
        env:
          VITE_CG_PUBLIC_URL: ${{secrets.VITE_CG_PUBLIC_URL}}
          VITE_CG_API_URL: ${{secrets.VITE_CG_API_URL}}
          VITE_SOCKET_SERVER_URL: ${{secrets.VITE_SOCKET_SERVER_URL}}
          VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
          VITE_SUPABASE_ANON_KEY: ${{secrets.VITE_SUPABASE_ANON_KEY}}
      - name: Publish
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{github.token}}
      - uses: actions/upload-artifact@v4
        with:
          name: Chatguessr-${{runner.os}}
          path: out/*/

