name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    name: Publish release
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Write .env
        run: node create-env.js
        env:
      - name: Publish
        run: npm run publish
        env:
          CG_PUBLIC_URL: ${{secrets.CG_PUBLIC_URL}}
          CG_API_URL: ${{secrets.CG_API_URL}}
          SOCKET_SERVER_URL: ${{secrets.SOCKET_SERVER_URL}}
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
          GITHUB_TOKEN: ${{github.token}}
      - uses: actions/upload-artifact@v3
        with:
          name: Chatguessr-${{runner.os}}
          path: out/*/

